services:
  - type: web
    name: topt-engine
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: PORT
        value: 10000
      - key: PREFIX
        value: topt
      - key: ALT_PREFIX
        value: t
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
